#!/bin/sh
# postinst script for shield-pam

set -e

#conffile move based on http://wiki.debian.org/DpkgConffileHandling
mv_conffile() {
    local OLDCONFFILE="$1"
    local NEWCONFFILE="$2"

    [ -e "$OLDCONFFILE" ] || return 0

    #If the old wasn't removed in preinst, maintainer didn't change
    #but user did, so preserve user change
    mv -f "$OLDCONFFILE" "$NEWCONFFILE"
}

case "$1" in
    configure)
    if [ ! -d /var/lib/pam_shield ]; then
    mkdir /var/lib/pam_shield
    fi
    touch /var/lib/pam_shield/db
    #conffile move based on http://wiki.debian.org/DpkgConffileHandling
    LASTVERSION="0.9.2-3.2"
    if dpkg --compare-versions "$2" le "$LASTVERSION"; then
    mv_conffile "/etc/cron.daily/pam_shield.cron" "/etc/cron.daily/pam_shield"
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    if [ -d /var/lib/pam_shield ]; then 
    rm -fr /var/lib/pam_shield
    fi
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

