#!/bin/sh
# postrm script for pam-shield
#

set -e

dpkg-maintscript-helper mv_conffile \
/etc/cron.daily/pam_shield.cron /etc/cron.daily/pam_shield 0.9.2-3.2 -- "$@"

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    if [ -d /var/lib/pam_shield ];
    then
    rm -fr /var/lib/pam_shield
    fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
