.TH SHIELD-TRIGGER-IPTABLES 8 " DEC 3 2007" "PAM-SHIELD 0.2.9" "pam-shield"
.SH NAME
\fBshield-trigger-iptables\fR \- Trigger iptables blocking rule
.SH SYNOPSIS
This file is not intended to be invoked manualy.
.SH DESCRIPTION
It is a halper script for locking out remote hosts with iptables rule.
.br	  
.SH COPYRIGHT
Copyright \(co 2007 by Walter de Jong <walter@heiho.net>
.br
This script is part of the PAM-shield package.
PAM-shield comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
